### PR TITLE
fix mapping of properties defined in super-interfaces

### PR DESCRIPTION
**Pull request by ChristophGr**
Issue #144

### CODE REVIEW

**Comment by ChristophGr** [comment]
Any news on this? This is still preventing us from upgrading to 0.7

**Comment by jhalterman** [comment]
Thanks for this!

**Comment by ChristophGr** [comment]
Any ETA for a new release? we could really use the fix

**Comment by jhalterman** [comment]
Just pushed 0.7.5. Cheers.

**Pull request merged**
