### PR TITLE
Fix NullPointerException in Erros.Converter.appliesTo

### LINKED ISSUE #155: NullPointerException as root cause in MappingException due to faulty error conversion
Errors.Converter.appliesTo throws NullPointerException in case target throws arbritrary exception during setting of property.

Here's is an example to reproduce the problem:

```Java
package org.modelmapper.internal;

import static org.testng.Assert.fail;

import org.modelmapper.MappingException;
import org.modelmapper.ModelMapper;
import org.testng.annotations.Test;

public class ErrorsTest {

  static class Source {
    public String getSource() { return null; }
  }

  static class Target{
    public void setSource(final String source) { if (source == null) throw new RuntimeException(); }
  }

  @Test(expectedExceptions = MappingException.class)
  public void shouldNotThrowNullPointerExceptionWhenSettingOfValueThrowsException() {
    try {
      new ModelMapper().map(new Source(), new Target());
    } catch(final MappingException e) {
      if (e.getCause() instanceof NullPointerException) {
        fail();
      } else {
        throw e;
      }
    }
  }

  @Test
  public void shouldNotThrowNullPointerExceptionDuringConvert() throws NoSuchMethodException {
    new Errors().errorSettingValue(this.getClass().getMethod("shouldNotThrowNullPointerExceptionDuringConvert"), null, null);
  }

}
```

### PR DESCRIPTION
**Pull request by sventorben**
Fixes #155

### CODE REVIEW

**Comment by jhalterman** [comment]
Thanks for this!

**Comment by sventorben** [comment]
Will there soon be a new release?  just asking, because this is bugging us a little.

**Comment by jhalterman** [comment]
0.7.5 is released!

**Comment by sventorben** [comment]
Great. Thx.

**Pull request merged**
